platform :ios, '8.0'
target ‘SSB_ChanYouJi’ do
  # pod '','~->'
  pod 'AFNetworking', '~> 3.1.0’
  pod 'SDWebImage', '~> 3.8.1'
  pod 'MJRefresh', '~>3.1.12'
  pod 'Mantle', '~>2.0.7'
  pod 'JSONModel', '~>1.3.0'
  pod 'Masonry', '~>1.0.1'
  pod 'CocoaAsyncSocket', '~>7.5.0'
  pod 'DateTools', '~>1.7.0'
  pod 'MJRefresh','~>3.1.12'
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'PPiAwesomeButton', '~> 1.5.2'
  pod 'CocoaLumberjack', '~> 2.3.0'
  pod 'DDLogger', '~> 1.1.4'
  
end
