platform :ios, '8.0'
target ‘SSCReminder’ do
  # pod '','~->'
  pod 'AFNetworking', '~> 3.1.0’
  pod 'SDWebImage', '~> 3.8.1'
  pod 'MJRefresh', '~>3.1.12'
  pod 'Mantle', '~>2.0.7'
  pod 'JSONModel', '~>1.3.0'
  pod 'Masonry', '~>1.0.1'
  pod 'DateTools', '~>1.7.0'
  pod 'MJRefresh','~>3.1.12'
  pod 'YYModel', '~> 1.0.4'
  
end