platform :ios, '8.0'
target ‘SSCDataManager’ do
  # pod '','~->'
  pod 'Mantle', '~>2.0.7'
  pod 'JSONModel', '~>1.3.0'
  pod 'DateTools', '~>1.7.0'
  pod 'MJRefresh','~>3.1.12'
  pod 'YYModel', '~> 1.0.4'
 pod 'FMDB', '~> 2.6.2'
  pod 'AFNetworking', '~> 3.1.0'
end
